from tkinter import Tk, Label, Button
from PIL import Image, ImageTk

logs = Tk()
logs.title("Kases aparāts")
logs.geometry('1600x1000')
gp = Button(logs, text='gaļa')
gp.place(x=100, y=50)
gp.config(height=5, width=25)
kp = Button(logs, text='Konditorija')
kp.place(x=370, y=50)  
kp.config(height=5, width=25)
zp = Button(logs, text='zivis')
zp.place(x=640, y=50)  
zp.config(height=5, width=25)
sp = Button(logs, text='Saldumi')
sp.place(x=100, y=200)
sp.config(height=5, width=25)
ag = Button(logs, text='Augļi')
ag.place(x=370, y=200)  
ag.config(height=5, width=25)
dz = Button(logs, text='Dārzeņi')
dz.place(x=640, y=200)  
dz.config(height=5, width=25)
sd = Button(logs, text='Saldējums')
sd.place(x=100, y=350)  
sd.config(height=5, width=25)
sp = Button(logs, text='Saldētie produkti')
sp.place(x=370, y=350)  
sp.config(height=5, width=25)
ri = Button(logs, text='Rieksti')
ri.place(x=640, y=350)  
ri.config(height=5, width=25)
ma = Button(logs, text="Maize")
ma.place(x=100, y=500)  
ma.config(height=5, width=25)
dzē = (logs, text='Dzērieni')
dzē.place(x=370, y=500)  
dzē.config(height=5, width=25)
alk = Button(logs, text='Alkahols')
alk.place(x=640, y=500)  
alk.config(height=5, width=25)
image = Image.open("user-icon-on-transparent-background-free-png.png")
resized_image = image.resize((100, 100))
photo = ImageTk.PhotoImage(resized_image)
button = Button(logs, image=photo, command=lambda: print("Button Clicked"))
button.place(x=600, y=950)  
logs.mainloop()
